# Generated by Django 6.0.5 on 2026-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='legal/'),
        ),
    ]
