# Generated by Django 6.0.5 on 2026-05-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_globalsetting_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='buttons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
