# Generated by Django 6.0.5 on 2026-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_automation_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='greeting_buttons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='greeting_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='greeting_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
